import React, { useState, useEffect } from 'react';
import adminApi from '../services/adminApi';
import DataTable from '../components/common/DataTable';
import LoadingSpinner from '../components/common/LoadingSpinner';
import { formatKES, formatDate } from '../utils/formatters';
import { RefreshCw } from 'lucide-react';

const OrdersPage = () => {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchOrders = async () => {
    setLoading(true);
    try {
      const { data } = await adminApi.get('/orders/all');
      setOrders(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchOrders(); }, []);

  const columns = [
    { header: 'Order ID', accessor: (row) => row._id.slice(-8), searchable: true },
    { header: 'User', accessor: (row) => row.user?.name || 'N/A', searchable: true },
    { header: 'Items', accessor: (row) => row.items.length },
    { header: 'Total', accessor: (row) => formatKES(row.totalAmount) },
    { header: 'Status', accessor: (row) => <span className="badge badge-success">{row.status}</span> },
    { header: 'Payment Method', accessor: (row) => row.paymentMethod === 'autogenerated' ? 'STK Push' : 'Manual' },
    { header: 'Date', accessor: (row) => formatDate(row.createdAt) },
  ];

  if (loading) return <LoadingSpinner />;

  return (
    <div>
      <div className="flex flex-wrap justify-between items-center gap-4 mb-6">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Orders</h1>
        <button onClick={fetchOrders} className="btn-secondary inline-flex items-center gap-2"><RefreshCw size={16} /> Refresh</button>
      </div>
      <div className="card">
        <div className="card-header"><h3 className="font-semibold">All Orders</h3></div>
        <div className="card-body">
          <DataTable columns={columns} data={orders} searchable searchPlaceholder="Search by order ID or user..." />
        </div>
      </div>
    </div>
  );
};

export default OrdersPage;